# Generated by Django 3.0.3 on 2020-05-04 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='massage',
            new_name='message',
        ),
    ]
