# Generated by Django 3.0.3 on 2020-05-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0002_auto_20200504_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='customer_tell',
            field=models.TextField(null=True),
        ),
    ]
