# Generated by Django 3.0.3 on 2020-05-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0003_auto_20200504_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vip.Designer'),
        ),
    ]
